#!/usr/bin/python3

'''Run a job with extrusion
'''

import fhs
import websocketd
import time

fhs.option('port', 'Port for connecting to Franklin', default = 'localhost:8000')
config = fhs.init(help = 'Automatic testing script for Franklin', version = '0.1', contact = 'Bas Wijnen <wijnen@debian.org>', packagename = 'franklin-test')

p = websocketd.RPC(config['port'])

jobname = 'auto-test-job'
if jobname in p.queue_list():
	p.queue_remove(jobname)

print('Adding job to queue')
p.queue_add('''\
G1 X0 Y0 Z150
G1 Z130
G1 Z110
G1 X10
G1 X0 Z150
''', jobname)

print('parking')
p.park()

print('running job')
p.queue_run(jobname)

print('parking')
p.park()
