#!/usr/bin/python

import network
import gui
import gtk

printer = network.RPCSocket ('reprap|')

class Controls (gtk.Table):
	def __init__ (self, g):
		gtk.Table.__init__ (self)

class Volume (gtk.DrawingArea):
	pass

g = gui.Gui ()
g (widgets = {'Controls': Controls, 'Volume': Volume}, events = {
	'stop': lambda: printer.stop (),
	'home': lambda: printer.home (),
	'homez': lambda: printer.home (only_z = True),
	'motorsoff': lambda: printer.sleep ()
	})
