#!/usr/bin/env python
import re
import sys

r = re.compile(r'\[!\((.*?)(?:<|\)!\]|\[\$\()', re.DOTALL)
event = re.compile(r'''\son\w+=(['"])(.*?)\1''', re.DOTALL)
comment = re.compile(r'\s+|(?://.*?)?\n', re.DOTALL)
data = sys.stdin.read()
print('var __checker__, node = {}, printer = {}, elements = [], stack = [];')
for i in r.findall(data):
	print('__checker__ = (' + comment.sub(' ', i) + ');')
for i in event.findall(data):
	print(i[1] + ';')
