#!/bin/bash
# flash-bbb - Flash new firmware to Melzi over Athena bridgeboard while preserving bootloader and EEPROM contents for Franklin
# Copyright 2014 Michigan Technological University
# Author: Bas Wijnen <wijnen@debian.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

tmp=`tempfile`

trap "rm '$tmp'" EXIT

config="${1:-/usr/lib/franklin/avrdude.conf}"
hex="${2:-/usr/lib/franklin/firmware/atmega1284p.hex}"

rom="`avrdude -q -q -C +"${config}" -c bbbmelzi -p atmega1284p -U eeprom:r:-:d`"
avrdude -q -q -C +"${config}" -c bbbmelzi -p atmega1284p -U flash:w:"${hex}":i
sed -e '/^:..00..00/d' < /usr/share/arduino/hardware/mighty-1284p/bootloaders/optiboot/optiboot_atmega1284p.hex > "$tmp"
avrdude -D -q -q -C +"${config}" -c bbbmelzi -p atmega1284p -U flash:w:"$tmp":i
avrdude -q -q -C +"${config}" -c bbbmelzi -p atmega1284p -U eeprom:w:$rom:m
