#!/usr/bin/python

import gtk
import interface

class App (gtk.EventBox):
	def __init__ (self):
		super (App, self).__init__ ()
		self.printer = interface.Printer ()
		self.home ()
		self.printer.motor_limit = 0
		self.printer.write_variables ()
		self.control = False
		self.shift = False
		self.axis = 0
		self.phase = 0
		self.z = 0.
		self.other = 0.
		self.add_events (gtk.gdk.KEY_PRESS_MASK | gtk.gdk.KEY_RELEASE_MASK)
		self.connect ('key_press_event', self.press)
		self.connect ('key_release_event', self.release)
		self.set_can_focus (True)
		self.label = gtk.Label ('You know what to do...')
		self.set_size_request (600, 400)
		self.add (self.label)
		self.label.show ()
	def home (self):
		self.printer.run_axis (0, 100)
		self.printer.run_axis (1, 100)
		self.printer.run_axis (2, 100)
		while len (self.printer.limits) < 3:
			self.printer.recv_packet (want_any = True)
		self.printer.limits.clear ()
		for i in range (3):
			self.printer.axis[i].set_current_pos (0)
		self.printer.goto (axes = {0:-10,1:-10,2:-10}, cb = True)
		while self.printer.movewait > 0:
			self.printer.recv_packet (want_any = True)
		self.printer.run_axis (0, 10)
		self.printer.run_axis (1, 10)
		self.printer.run_axis (2, 10)
		while len (self.printer.limits) < 3:
			self.printer.recv_packet (want_any = True)
		self.printer.limits.clear ()
		for i in range (3):
			self.printer.axis[i].set_current_pos (0)
	def get_amount (self):
		if self.control:
			return .1
		if self.shift:
			return 10
		return 1
	def move (self, dz, dother):
		if self.phase >= 8:
			dz = 0
		self.z += dz
		self.other += dother
		axes = {0: self.other, 1: self.other, 2: self.other}
		if self.axis >= 0:
			axes[self.axis] += self.z
		self.printer.goto (axes = axes)
	def press (self, widget, event):
		if event.keyval == gtk.keysyms.Up:
			self.move (0, self.get_amount ())
		elif event.keyval == gtk.keysyms.Down:
			self.move (0, -self.get_amount ())
		elif event.keyval == gtk.keysyms.Left:
			self.move (-self.get_amount (), 0)
		elif event.keyval == gtk.keysyms.Right:
			self.move (self.get_amount (), 0)
		elif event.keyval == gtk.keysyms.Shift_L:
			self.shift = True
		elif event.keyval == gtk.keysyms.Control_L:
			self.control = True
		elif event.keyval == gtk.keysyms.Return:
			if self.phase == 0:
				self.z0 = self.z
				self.zs = []
			print '%d %d %f %f' % (self.axis, (self.phase % 8) * 10, self.z, self.other)
			if self.phase <= 7:
				self.zs.append ((self.z, self.other))
			self.phase += 1
			if self.phase == 16:
				self.phase = 0
				if self.z > self.other:
					self.move (0, -self.other / 2)
					self.move (-self.z, 0)
				else:
					self.move (-self.z, 0)
					self.move (0, -self.other / 2)
				self.axis += 1
				if self.axis >= 3:
					gtk.main_quit ()
				return
			if self.phase >= 8:
				c = self.zs[self.phase - 8]
				self.phase -= 8
				if c[1] > self.other:
					self.move (0, c[1] - self.other)
					self.move (c[0] - self.z, 0)
				else:
					self.move (c[0] - self.z, 0)
					print c[1], self.other
					self.move (0, c[1] - self.other)
				self.phase += 8
	def release (self, widget, event):
		if event.keyval == gtk.keysyms.ISO_Prev_Group:
			self.shift = False
		elif event.keyval == gtk.keysyms.Control_L:
			self.control = False
	def quit (self, x):
		self.printer.motor_limit = 10000
		self.printer.write_variables ()
		gtk.main_quit ()

w = gtk.Window ()
a = App ()
w.add (a)
w.connect ('destroy', a.quit)
a.show ()
w.show ()
gtk.main ()
for i in range (3):
	a.printer.sleep_axis (i)
