#!/usr/bin/python

import printer3d
import math
import wave
import sys

wavefile = wave.open (sys.argv[1])
data = [ord (x) for x in wavefile.readframes (wavefile.getnframes ())]
minimum = min (data)
maximum = max (data)
data = [int ((x - (minimum + maximum) / 2.) / (maximum - minimum) * 7.99 + 4) for x in data]
d = ''
for pos in range (0, len (data) - 7, 8):
	d += chr ((data[pos + 0] | data[pos + 1] << 3 | data[pos + 2] << 6) & 0xff)
	d += chr ((data[pos + 2] >> 2 | data[pos + 3] << 1 | data[pos + 4] << 4 | data[pos + 5] << 7) & 0xff)
	d += chr ((data[pos + 5] >> 1 | data[pos + 6] << 2 | data[pos + 7] << 5) & 0xff)

p = printer3d.Printer ()
p.play (d)
while True:
	p.recv_packet (want_any = True)
